name: Login, build and push to Docker

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
         name: Docker build
         run: |
           docker build ./docker-app -t reactapp
      -
         name: Docker push
         run: |
           docker push hakimharith/reactapp
