name: Login, build and push to Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER.PASSWORD
      - name: docker build
        run: |
          docker build ./docker-app -t reactapp
      - name: docker push
        run: |
          docker push $DOCKER_USERNAME/reactapp
          
